### ISSUE TITLE
Kill xi-core after the program has exited

### ISSUE THREAD

**Issue by Cogitri** [xi-frontend/xrl#34]
I guess this might be on gxi not calling some required function during shutdown, but right now gxi leaves behind a `xi-core` process every time :/

**Comment by little-dude** [comment]
oh right, I hadn't even thought about this.

**Comment by Cogitri** [comment]
I thought about this for a bit and I think a shutdown method for Client would be the simplest thing to do. We _could_ implement a custom `Drop` for `InnerClient` too, but I'm not sure if we would leave an xi-editor process behind then if a reference loop is created on runtime.

**Comment by little-dude** [comment]
I just looked at this, and from what I understand, the process should `SIGKILL`ed when the `Endpoint` is dropped as documented in `[`tokio::process::Child`](https://docs.rs/tokio-process/0.2.3/tokio_process/struct.Child.html):

>  If a `tokio_process::Child` is dropped before the process finishes then the process will be terminated.

Since this `Child` is wrapped into `xrl::Core`, which is itself wrapped into `xrl::Endpoint`, the process should be killed when the `Endpoint` is dropped (either because it finishes, or because the executor exits and drops all its futures).

**Comment by Cogitri** [comment]
Huh, that doesn't seem the case, at least for tau:

![Screenshot from 2019-06-16 10-58-44](https://user-images.githubusercontent.com/8766773/59561897-ba949480-9025-11e9-8a18-feb32139a8c2.png)

Seems like it works for xi-term though, hum.

**Comment by Cogitri** [comment]
Oops, forgot to kill the thread I run tokio on, my bad :P
